// GENERATED by `just fund` (scripts/wire-apps.mjs) from deployment.testnet.json. Do not edit by hand.
// The public identifiers the extension pins to Troia's deployment.

export const WALLET_BRIDGE_URL = "https://troia-extension.vercel.app/wallet";

export const USDC_ISSUER = 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5';

export const BACKEND_BASE_URL = 'https://troia-extension.vercel.app/api';

export const STOREFRONT_ORIGINS = [
  'http://localhost:5173',
  'http://127.0.0.1:5173',
  'http://localhost:5174',
  'http://127.0.0.1:5174',
  'https://troia-demo-store.vercel.app',
  'https://troia-extension.vercel.app',
] as const;
