// GENERATED by `just fund` (scripts/wire-apps.mjs) from deployment.testnet.json. Do not edit by hand.
// The public identifiers the extension pins to Troia's deployment.

export const USDC_ISSUER = 'GCRAO5VCCWUSHAOJ5LDVGD2T6HSIRBPEU4TDY6XP4GSVTOTO2KZI4N5W';

export const BACKEND_BASE_URL = 'http://localhost:3000';

export const STOREFRONT_ORIGINS = [
  'http://localhost:5173',
  'http://127.0.0.1:5173',
] as const;
