import { describe, expect, it } from 'vitest';
import { classifyAddress } from '../src/index.js';

// Fixed, real StrKey addresses generated by @stellar/stellar-base (deterministic seeds).
const G = 'GDVEU3DD4KOFECV66VIHWEZOYX4ZKR3WV27L464SIIPOU2IUI3JCZA57';
const C = 'CAEQSCIJBEEQSCIJBEEQSCIJBEEQSCIJBEEQSCIJBEEQSCIJBEEQTD2L';

describe('classifyAddress', () => {
  it('classifies a valid G address as ed25519', () => {
    expect(classifyAddress(G)).toBe('ed25519');
  });

  it('classifies a valid C address as contract', () => {
    expect(classifyAddress(C)).toBe('contract');
  });

  it('rejects a corrupted checksum (single character changed in the payload)', () => {
    const swapped = G[10] === 'A' ? 'B' : 'A';
    const bad = G.slice(0, 10) + swapped + G.slice(11);
    expect(classifyAddress(bad)).toBe('invalid');
  });

  it('rejects wrong length (truncated or extended)', () => {
    expect(classifyAddress(G.slice(0, 55))).toBe('invalid');
    expect(classifyAddress(G + 'A')).toBe('invalid');
  });

  it('rejects lowercase (StrKey is uppercase base32)', () => {
    expect(classifyAddress(G.toLowerCase())).toBe('invalid');
  });

  it('rejects empty and junk', () => {
    expect(classifyAddress('')).toBe('invalid');
    expect(classifyAddress('not-an-address')).toBe('invalid');
  });
});
