// GENERATED by `just fund` (scripts/wire-apps.mjs) from deployment.testnet.json. Do not edit by hand.
// The public identifiers the storefront pins to Troia's deployment.

export const USDC_ISSUER = 'GCRAO5VCCWUSHAOJ5LDVGD2T6HSIRBPEU4TDY6XP4GSVTOTO2KZI4N5W';
