// GENERATED by `just fund` (scripts/wire-apps.mjs) from deployment.testnet.json. Do not edit by hand.
// The public identifiers the storefront pins to Troia's deployment.

export const USDC_ISSUER = 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5';
