import { describe, expect, it } from 'vitest';
import { isValidStellarPublicKey } from '../src/lib/strkey';

const MERCHANT = 'GA4WBDANMT6MF6VMFFKMZIR6QE2XBEETNHANAMRBQC2XGSST3GRNIESX';
const ISSUER = 'GCRAO5VCCWUSHAOJ5LDVGD2T6HSIRBPEU4TDY6XP4GSVTOTO2KZI4N5W';
// A third real ed25519 address generated by @stellar/stellar-base (from the core package's own fixtures).
const SDK_G = 'GDVEU3DD4KOFECV66VIHWEZOYX4ZKR3WV27L464SIIPOU2IUI3JCZA57';

describe('isValidStellarPublicKey', () => {
  it('accepts real ed25519 public keys', () => {
    expect(isValidStellarPublicKey(MERCHANT)).toBe(true);
    expect(isValidStellarPublicKey(ISSUER)).toBe(true);
    expect(isValidStellarPublicKey(SDK_G)).toBe(true);
  });

  it('rejects a corrupted checksum (one payload character changed)', () => {
    const swapped = MERCHANT[10] === 'A' ? 'B' : 'A';
    expect(isValidStellarPublicKey(MERCHANT.slice(0, 10) + swapped + MERCHANT.slice(11))).toBe(
      false,
    );
  });

  it('rejects wrong length (truncated or extended)', () => {
    expect(isValidStellarPublicKey(MERCHANT.slice(0, 55))).toBe(false);
    expect(isValidStellarPublicKey(MERCHANT + 'A')).toBe(false);
  });

  it('rejects lowercase (StrKey is uppercase base32)', () => {
    expect(isValidStellarPublicKey(MERCHANT.toLowerCase())).toBe(false);
  });

  it('rejects a non-G prefix (e.g. a secret S... key)', () => {
    expect(isValidStellarPublicKey('S' + MERCHANT.slice(1))).toBe(false);
  });

  it('rejects a wrong version byte that still passes the format regex', () => {
    // 56 uppercase base32 chars starting with G, but the decoded version byte is not 0x30.
    expect(isValidStellarPublicKey('G'.repeat(56))).toBe(false);
  });

  it('rejects invalid base32 characters (0, 1, 8, 9)', () => {
    expect(isValidStellarPublicKey('G0' + MERCHANT.slice(2))).toBe(false);
  });

  it('rejects empty and junk', () => {
    expect(isValidStellarPublicKey('')).toBe(false);
    expect(isValidStellarPublicKey('not-an-address')).toBe(false);
  });
});
