// Point the storefront and the browser extension at Troia's deployment.
//
// Troia's fixed on-chain identity — the USDC issuer, its SAC, the TroyPool, the operator and admin — lives in
// deployment.testnet.json. The two apps are standalone npm packages that cannot import `@troia/config`, so each
// keeps its own config module; until now those modules hard-coded the issuer, which meant a clone that ran
// `just bootstrap` built an extension whose allowlist rejected the clone's own USDC, failed closed, and never
// showed the banner. The demo looked broken and nothing said why.
//
// What is written here is ONLY the issuer. The merchant is deliberately absent: which shop is being paid is the
// shop's business, and the shop declares it in its own SEP-7 request. The extension settles USDC; it does not
// keep a guest list. The storefront's own payee stays in the storefront's own config.
//
// The written files are COMMITTED (public identifiers, never secrets) so a fresh clone type-checks and CI stays
// green before anyone has run anything.

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

let dep;
try {
  dep = JSON.parse(readFileSync(join(ROOT, 'deployment.testnet.json'), 'utf8'));
} catch {
  console.error('no deployment.testnet.json — see `just fund` (it explains what to do)');
  process.exit(1);
}
const issuer = dep.usdcIssuer;
if (typeof issuer !== 'string' || !/^G[A-Z2-7]{55}$/.test(issuer)) {
  console.error(`deployment.testnet.json: usdcIssuer is not a Stellar public key: ${issuer}`);
  process.exit(1);
}

const backendUrl = dep.backendUrl;
const storefrontOrigins = dep.storefrontOrigins;
if (typeof backendUrl !== 'string' || !/^https?:\/\//.test(backendUrl)) {
  console.error(`deployment.testnet.json: backendUrl is not an http(s) origin: ${backendUrl}`);
  process.exit(1);
}
if (!Array.isArray(storefrontOrigins) || storefrontOrigins.length === 0) {
  console.error('deployment.testnet.json: storefrontOrigins must be a non-empty array');
  process.exit(1);
}
for (const o of storefrontOrigins) {
  if (typeof o !== 'string' || !/^https?:\/\/[^/]+$/.test(o)) {
    console.error(`deployment.testnet.json: storefrontOrigins entry is not a bare origin: ${o}`);
    process.exit(1);
  }
}

const HEAD = (what) =>
  `// GENERATED by \`just fund\` (scripts/wire-apps.mjs) from deployment.testnet.json. Do not edit by hand.\n` +
  `// The public identifiers the ${what} pins to Troia's deployment.\n\n`;

writeFileSync(
  join(ROOT, 'app/storefront/src/deployment.generated.ts'),
  HEAD('storefront') + `export const USDC_ISSUER = '${issuer}';\n`,
);

writeFileSync(
  join(ROOT, 'app/extension/src/lib/deployment.generated.ts'),
  HEAD('extension') +
    `export const USDC_ISSUER = '${issuer}';\n\n` +
    `export const BACKEND_BASE_URL = '${backendUrl}';\n\n` +
    `export const STOREFRONT_ORIGINS = [\n` +
    storefrontOrigins.map((o) => `  '${o}',`).join('\n') +
    `\n] as const;\n`,
);

console.log(`wired the apps to Troia's deployment:
  usdcIssuer         ${issuer}
  backendUrl         ${backendUrl}
  storefrontOrigins  ${storefrontOrigins.join(', ')}
  wrote app/storefront/src/deployment.generated.ts
  wrote app/extension/src/lib/deployment.generated.ts

Rebuild the extension before loading it in Chrome:  cd app/extension && npm run build`);
